name: dev build

on:
  push:
    branches:
      - main
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create builder
        run: make buildx-machine
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: build/Dockerfile
          tags: ${{ secrets.DEV_BUILD_REPOSITORY }}/registry-adapter:latest
          build-args: |
            COMMIT=${{ github.sha }}
            VERSION=${{ github.ref_name }}

